## Fitting Models
## 1 signifies total data, 2=winData, 3=losData, 4=drawData
## fit means that Black is dependent on White
## revfit means white is dependent on Black
## fit{1,2,3,4}{Piece/Move} means that Black Piece or Black move is dependent on All the 6 other White Moves
## revfit{1,2,3,4}{piece/Move} means that white Piece or white move is dependent on All the 6 other Black Moves
## fit{1,2,3,4}{Initial of Black Piece/Move}{initial of White piece/Move} means that Black piece/move is dependent on only 
## the other white piece/move
## revfit{1,2,3,4}{Initial of White Piece/Move}{initial of Black Piece/Move} means that White piece/Move is dependent on only
## the other Black piece/move


## Black is dependent on White

fit1 <- lm(B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves ~ 
             W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, data)
fit2 <- lm(B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves ~ 
             W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, winData)
fit3 <- lm(B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves ~ 
             W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, losData)
fit4 <- lm(B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves ~ 
             W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, drawData)

## white is dependent on Black
revfit1 <- lm(W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves ~ 
                B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, data)
revfit2 <- lm(W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves ~ 
                B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, winData)
revfit3 <- lm(W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves ~ 
                B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, losData)
revfit4 <- lm(W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves ~ 
                B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, drawData)


## Black Piece or Black move is dependent on All the 6 other White Moves

fit1Bishop <- lm(B_B_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, data)
fit2Bishop <- lm(B_B_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, winData)
fit3Bishop <- lm(B_B_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, losData)
fit4Bishop <- lm(B_B_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, drawData)
fit1King <- lm(B_K_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, data)
fit2King <- lm(B_K_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, winData)
fit3King <- lm(B_K_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, losData)
fit4King <- lm(B_K_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, drawData)
fit1Knight <- lm(B_N_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, data)
fit2Knight <- lm(B_N_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, winData)
fit3Knight <- lm(B_N_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, losData)
fit4Knight <- lm(B_N_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, drawData)
fit1Castle <- lm(B_O_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, data)
fit2Castle <- lm(B_O_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, winData)
fit3Castle <- lm(B_O_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, losData)
fit4Castle <- lm(B_O_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, drawData)
fit1Queen <- lm(B_Q_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, data)
fit2Queen <- lm(B_Q_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, winData)
fit3Queen <- lm(B_Q_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, losData)
fit4Queen <- lm(B_Q_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, drawData)
fit1Rook <- lm(B_R_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, data)
fit2Rook <- lm(B_R_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, winData)
fit3Rook <- lm(B_R_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, losData)
fit4Rook <- lm(B_R_moves~W_B_moves+W_K_moves+W_N_moves+W_O_moves+W_Q_moves+W_R_moves, drawData)

## white Piece or white move is dependent on All the 6 other Black Moves

revfit1Bishop <- lm(W_B_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, data)
revfit2Bishop <- lm(W_B_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, winData)
revfit3Bishop <- lm(W_B_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, losData)
revfit4Bishop <- lm(W_B_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, drawData)
revfit1King <- lm(W_K_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, data)
revfit2King <- lm(W_K_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, winData)
revfit3King <- lm(W_K_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, losData)
revfit4King <- lm(W_K_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, drawData)
revfit1Knight <- lm(W_N_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, data)
revfit2Knight <- lm(W_N_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, winData)
revfit3Knight <- lm(W_N_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, losData)
revfit4Knight <- lm(W_N_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, drawData)
revfit1Castle <- lm(W_O_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, data)
revfit2Castle <- lm(W_O_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, winData)
revfit3Castle <- lm(W_O_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, losData)
revfit4Castle <- lm(W_O_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, drawData)
revfit1Queen <- lm(W_Q_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, data)
revfit2Queen <- lm(W_Q_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, winData)
revfit3Queen <- lm(W_Q_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, losData)
revfit4Queen <- lm(W_Q_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, drawData)
revfit1Rook <- lm(W_R_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, data)
revfit2Rook <- lm(W_R_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, winData)
revfit3Rook <- lm(W_R_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, losData)
revfit4Rook <- lm(W_R_moves~B_B_moves+B_K_moves+B_N_moves+B_O_moves+B_Q_moves+B_R_moves, drawData)


## Black piece/move is dependent on only the other white piece/move

fit1BB <- lm(B_B_moves~W_B_moves,data)
fit2BB <- lm(B_B_moves~W_B_moves,winData)
fit3BB <- lm(B_B_moves~W_B_moves,losData)
fit4BB <- lm(B_B_moves~W_B_moves,drawData)
fit1BK <- lm(B_B_moves~W_K_moves,data)
fit2BK <- lm(B_B_moves~W_K_moves,winData)
fit3BK <- lm(B_B_moves~W_K_moves,losData)
fit4BK <- lm(B_B_moves~W_K_moves,drawData)
fit1BN <- lm(B_B_moves~W_N_moves,data)
fit2BN <- lm(B_B_moves~W_N_moves,winData)
fit3BN <- lm(B_B_moves~W_N_moves,losData)
fit4BN <- lm(B_B_moves~W_N_moves,drawData)
fit1BO <- lm(B_B_moves~W_O_moves,data)
fit2BO <- lm(B_B_moves~W_O_moves,winData)
fit3BO <- lm(B_B_moves~W_O_moves,losData)
fit4BO <- lm(B_B_moves~W_O_moves,drawData)
fit1BQ <- lm(B_B_moves~W_Q_moves,data)
fit2BQ <- lm(B_B_moves~W_Q_moves,winData)
fit3BQ <- lm(B_B_moves~W_Q_moves,losData)
fit4BQ <- lm(B_B_moves~W_Q_moves,drawData)
fit1BR <- lm(B_B_moves~W_R_moves,data)
fit2BR <- lm(B_B_moves~W_R_moves,winData)
fit3BR <- lm(B_B_moves~W_R_moves,losData)
fit4BR <- lm(B_B_moves~W_R_moves,drawData)


fit1KB <- lm(B_K_moves~W_B_moves,data)
fit2KB <- lm(B_K_moves~W_B_moves,winData)
fit3KB <- lm(B_K_moves~W_B_moves,losData)
fit4KB <- lm(B_K_moves~W_B_moves,drawData)
fit1KK <- lm(B_K_moves~W_K_moves,data)
fit2KK <- lm(B_K_moves~W_K_moves,winData)
fit3KK <- lm(B_K_moves~W_K_moves,losData)
fit4KK <- lm(B_K_moves~W_K_moves,drawData)
fit1KN <- lm(B_K_moves~W_N_moves,data)
fit2KN <- lm(B_K_moves~W_N_moves,winData)
fit3KN <- lm(B_K_moves~W_N_moves,losData)
fit4KN <- lm(B_K_moves~W_N_moves,drawData)
fit1KO <- lm(B_K_moves~W_O_moves,data)
fit2KO <- lm(B_K_moves~W_O_moves,winData)
fit3KO <- lm(B_K_moves~W_O_moves,losData)
fit4KO <- lm(B_K_moves~W_O_moves,drawData)
fit1KQ <- lm(B_K_moves~W_Q_moves,data)
fit2KQ <- lm(B_K_moves~W_Q_moves,winData)
fit3KQ <- lm(B_K_moves~W_Q_moves,losData)
fit4KQ <- lm(B_K_moves~W_Q_moves,drawData)
fit1KR <- lm(B_K_moves~W_R_moves,data)
fit2KR <- lm(B_K_moves~W_R_moves,winData)
fit3KR <- lm(B_K_moves~W_R_moves,losData)
fit4KR <- lm(B_K_moves~W_R_moves,drawData)



fit1NB <- lm(B_N_moves~W_B_moves,data)
fit2NB <- lm(B_N_moves~W_B_moves,winData)
fit3NB <- lm(B_N_moves~W_B_moves,losData)
fit4NB <- lm(B_N_moves~W_B_moves,drawData)
fit1NK <- lm(B_N_moves~W_K_moves,data)
fit2NK <- lm(B_N_moves~W_K_moves,winData)
fit3NK <- lm(B_N_moves~W_K_moves,losData)
fit4NK <- lm(B_N_moves~W_K_moves,drawData)
fit1NN <- lm(B_N_moves~W_N_moves,data)
fit2NN <- lm(B_N_moves~W_N_moves,winData)
fit3NN <- lm(B_N_moves~W_N_moves,losData)
fit4NN <- lm(B_N_moves~W_N_moves,drawData)
fit1NO <- lm(B_N_moves~W_O_moves,data)
fit2NO <- lm(B_N_moves~W_O_moves,winData)
fit3NO <- lm(B_N_moves~W_O_moves,losData)
fit4NO <- lm(B_N_moves~W_O_moves,drawData)
fit1NQ <- lm(B_N_moves~W_Q_moves,data)
fit2NQ <- lm(B_N_moves~W_Q_moves,winData)
fit3NQ <- lm(B_N_moves~W_Q_moves,losData)
fit4NQ <- lm(B_N_moves~W_Q_moves,drawData)
fit1NR <- lm(B_N_moves~W_R_moves,data)
fit2NR <- lm(B_N_moves~W_R_moves,winData)
fit3NR <- lm(B_N_moves~W_R_moves,losData)
fit4NR <- lm(B_N_moves~W_R_moves,drawData)

fit1OB <- lm(B_O_moves~W_B_moves,data)
fit2OB <- lm(B_O_moves~W_B_moves,winData)
fit3OB <- lm(B_O_moves~W_B_moves,losData)
fit4OB <- lm(B_O_moves~W_B_moves,drawData)
fit1OK <- lm(B_O_moves~W_K_moves,data)
fit2OK <- lm(B_O_moves~W_K_moves,winData)
fit3OK <- lm(B_O_moves~W_K_moves,losData)
fit4OK <- lm(B_O_moves~W_K_moves,drawData)
fit1ON <- lm(B_O_moves~W_N_moves,data)
fit2ON <- lm(B_O_moves~W_N_moves,winData)
fit3ON <- lm(B_O_moves~W_N_moves,losData)
fit4ON <- lm(B_O_moves~W_N_moves,drawData)
fit1OO <- lm(B_O_moves~W_O_moves,data)
fit2OO <- lm(B_O_moves~W_O_moves,winData)
fit3OO <- lm(B_O_moves~W_O_moves,losData)
fit4OO <- lm(B_O_moves~W_O_moves,drawData)
fit1OQ <- lm(B_O_moves~W_Q_moves,data)
fit2OQ <- lm(B_O_moves~W_Q_moves,winData)
fit3OQ <- lm(B_O_moves~W_Q_moves,losData)
fit4OQ <- lm(B_O_moves~W_Q_moves,drawData)
fit1OR <- lm(B_O_moves~W_R_moves,data)
fit2OR <- lm(B_O_moves~W_R_moves,winData)
fit3OR <- lm(B_O_moves~W_R_moves,losData)
fit4OR <- lm(B_O_moves~W_R_moves,drawData)

fit1QB <- lm(B_Q_moves~W_B_moves,data)
fit2QB <- lm(B_Q_moves~W_B_moves,winData)
fit3QB <- lm(B_Q_moves~W_B_moves,losData)
fit4QB <- lm(B_Q_moves~W_B_moves,drawData)
fit1QK <- lm(B_Q_moves~W_K_moves,data)
fit2QK <- lm(B_Q_moves~W_K_moves,winData)
fit3QK <- lm(B_Q_moves~W_K_moves,losData)
fit4QK <- lm(B_Q_moves~W_K_moves,drawData)
fit1QN <- lm(B_Q_moves~W_N_moves,data)
fit2QN <- lm(B_Q_moves~W_N_moves,winData)
fit3QN <- lm(B_Q_moves~W_N_moves,losData)
fit4QN <- lm(B_Q_moves~W_N_moves,drawData)
fit1QO <- lm(B_Q_moves~W_O_moves,data)
fit2QO <- lm(B_Q_moves~W_O_moves,winData)
fit3QO <- lm(B_Q_moves~W_O_moves,losData)
fit4QO <- lm(B_Q_moves~W_O_moves,drawData)
fit1QQ <- lm(B_Q_moves~W_Q_moves,data)
fit2QQ <- lm(B_Q_moves~W_Q_moves,winData)
fit3QQ <- lm(B_Q_moves~W_Q_moves,losData)
fit4QQ <- lm(B_Q_moves~W_Q_moves,drawData)
fit1QR <- lm(B_Q_moves~W_R_moves,data)
fit2QR <- lm(B_Q_moves~W_R_moves,winData)
fit3QR <- lm(B_Q_moves~W_R_moves,losData)
fit4QR <- lm(B_Q_moves~W_R_moves,drawData)

fit1RB <- lm(B_R_moves~W_B_moves,data)
fit2RB <- lm(B_R_moves~W_B_moves,winData)
fit3RB <- lm(B_R_moves~W_B_moves,losData)
fit4RB <- lm(B_R_moves~W_B_moves,drawData)
fit1RK <- lm(B_R_moves~W_K_moves,data)
fit2RK <- lm(B_R_moves~W_K_moves,winData)
fit3RK <- lm(B_R_moves~W_K_moves,losData)
fit4RK <- lm(B_R_moves~W_K_moves,drawData)
fit1RN <- lm(B_R_moves~W_N_moves,data)
fit2RN <- lm(B_R_moves~W_N_moves,winData)
fit3RN <- lm(B_R_moves~W_N_moves,losData)
fit4RN <- lm(B_R_moves~W_N_moves,drawData)
fit1RO <- lm(B_R_moves~W_O_moves,data)
fit2RO <- lm(B_R_moves~W_O_moves,winData)
fit3RO <- lm(B_R_moves~W_O_moves,losData)
fit4RO <- lm(B_R_moves~W_O_moves,drawData)
fit1RQ <- lm(B_R_moves~W_Q_moves,data)
fit2RQ <- lm(B_R_moves~W_Q_moves,winData)
fit3RQ <- lm(B_R_moves~W_Q_moves,losData)
fit4RQ <- lm(B_R_moves~W_Q_moves,drawData)
fit1RR <- lm(B_R_moves~W_R_moves,data)
fit2RR <- lm(B_R_moves~W_R_moves,winData)
fit3RR <- lm(B_R_moves~W_R_moves,losData)
fit4RR <- lm(B_R_moves~W_R_moves,drawData)


## White piece/Move is dependent on only the other Black piece/move

revfit1BB <- lm(W_B_moves~B_B_moves,data)
revfit2BB <- lm(W_B_moves~B_B_moves,winData)
revfit3BB <- lm(W_B_moves~B_B_moves,losData)
revfit4BB <- lm(W_B_moves~B_B_moves,drawData)
revfit1BK <- lm(W_B_moves~B_K_moves,data)
revfit2BK <- lm(W_B_moves~B_K_moves,winData)
revfit3BK <- lm(W_B_moves~B_K_moves,losData)
revfit4BK <- lm(W_B_moves~B_K_moves,drawData)
revfit1BN <- lm(W_B_moves~B_N_moves,data)
revfit2BN <- lm(W_B_moves~B_N_moves,winData)
revfit3BN <- lm(W_B_moves~B_N_moves,losData)
revfit4BN <- lm(W_B_moves~B_N_moves,drawData)
revfit1BO <- lm(W_B_moves~B_O_moves,data)
revfit2BO <- lm(W_B_moves~B_O_moves,winData)
revfit3BO <- lm(W_B_moves~B_O_moves,losData)
revfit4BO <- lm(W_B_moves~B_O_moves,drawData)
revfit1BQ <- lm(W_B_moves~B_Q_moves,data)
revfit2BQ <- lm(W_B_moves~B_Q_moves,winData)
revfit3BQ <- lm(W_B_moves~B_Q_moves,losData)
revfit4BQ <- lm(W_B_moves~B_Q_moves,drawData)
revfit1BR <- lm(W_B_moves~B_R_moves,data)
revfit2BR <- lm(W_B_moves~B_R_moves,winData)
revfit3BR <- lm(W_B_moves~B_R_moves,losData)
revfit4BR <- lm(W_B_moves~B_R_moves,drawData)


revfit1KB <- lm(W_K_moves~B_B_moves,data)
revfit2KB <- lm(W_K_moves~B_B_moves,winData)
revfit3KB <- lm(W_K_moves~B_B_moves,losData)
revfit4KB <- lm(W_K_moves~B_B_moves,drawData)
revfit1KK <- lm(W_K_moves~B_K_moves,data)
revfit2KK <- lm(W_K_moves~B_K_moves,winData)
revfit3KK <- lm(W_K_moves~B_K_moves,losData)
revfit4KK <- lm(W_K_moves~B_K_moves,drawData)
revfit1KN <- lm(W_K_moves~B_N_moves,data)
revfit2KN <- lm(W_K_moves~B_N_moves,winData)
revfit3KN <- lm(W_K_moves~B_N_moves,losData)
revfit4KN <- lm(W_K_moves~B_N_moves,drawData)
revfit1KO <- lm(W_K_moves~B_O_moves,data)
revfit2KO <- lm(W_K_moves~B_O_moves,winData)
revfit3KO <- lm(W_K_moves~B_O_moves,losData)
revfit4KO <- lm(W_K_moves~B_O_moves,drawData)
revfit1KQ <- lm(W_K_moves~B_Q_moves,data)
revfit2KQ <- lm(W_K_moves~B_Q_moves,winData)
revfit3KQ <- lm(W_K_moves~B_Q_moves,losData)
revfit4KQ <- lm(W_K_moves~B_Q_moves,drawData)
revfit1KR <- lm(W_K_moves~B_R_moves,data)
revfit2KR <- lm(W_K_moves~B_R_moves,winData)
revfit3KR <- lm(W_K_moves~B_R_moves,losData)
revfit4KR <- lm(W_K_moves~B_R_moves,drawData)



revfit1NB <- lm(W_N_moves~B_B_moves,data)
revfit2NB <- lm(W_N_moves~B_B_moves,winData)
revfit3NB <- lm(W_N_moves~B_B_moves,losData)
revfit4NB <- lm(W_N_moves~B_B_moves,drawData)
revfit1NK <- lm(W_N_moves~B_K_moves,data)
revfit2NK <- lm(W_N_moves~B_K_moves,winData)
revfit3NK <- lm(W_N_moves~B_K_moves,losData)
revfit4NK <- lm(W_N_moves~B_K_moves,drawData)
revfit1NN <- lm(W_N_moves~B_N_moves,data)
revfit2NN <- lm(W_N_moves~B_N_moves,winData)
revfit3NN <- lm(W_N_moves~B_N_moves,losData)
revfit4NN <- lm(W_N_moves~B_N_moves,drawData)
revfit1NO <- lm(W_N_moves~B_O_moves,data)
revfit2NO <- lm(W_N_moves~B_O_moves,winData)
revfit3NO <- lm(W_N_moves~B_O_moves,losData)
revfit4NO <- lm(W_N_moves~B_O_moves,drawData)
revfit1NQ <- lm(W_N_moves~B_Q_moves,data)
revfit2NQ <- lm(W_N_moves~B_Q_moves,winData)
revfit3NQ <- lm(W_N_moves~B_Q_moves,losData)
revfit4NQ <- lm(W_N_moves~B_Q_moves,drawData)
revfit1NR <- lm(W_N_moves~B_R_moves,data)
revfit2NR <- lm(W_N_moves~B_R_moves,winData)
revfit3NR <- lm(W_N_moves~B_R_moves,losData)
revfit4NR <- lm(W_N_moves~B_R_moves,drawData)

revfit1OB <- lm(W_O_moves~B_B_moves,data)
revfit2OB <- lm(W_O_moves~B_B_moves,winData)
revfit3OB <- lm(W_O_moves~B_B_moves,losData)
revfit4OB <- lm(W_O_moves~B_B_moves,drawData)
revfit1OK <- lm(W_O_moves~B_K_moves,data)
revfit2OK <- lm(W_O_moves~B_K_moves,winData)
revfit3OK <- lm(W_O_moves~B_K_moves,losData)
revfit4OK <- lm(W_O_moves~B_K_moves,drawData)
revfit1ON <- lm(W_O_moves~B_N_moves,data)
revfit2ON <- lm(W_O_moves~B_N_moves,winData)
revfit3ON <- lm(W_O_moves~B_N_moves,losData)
revfit4ON <- lm(W_O_moves~B_N_moves,drawData)
revfit1OO <- lm(W_O_moves~B_O_moves,data)
revfit2OO <- lm(W_O_moves~B_O_moves,winData)
revfit3OO <- lm(W_O_moves~B_O_moves,losData)
revfit4OO <- lm(W_O_moves~B_O_moves,drawData)
revfit1OQ <- lm(W_O_moves~B_Q_moves,data)
revfit2OQ <- lm(W_O_moves~B_Q_moves,winData)
revfit3OQ <- lm(W_O_moves~B_Q_moves,losData)
revfit4OQ <- lm(W_O_moves~B_Q_moves,drawData)
revfit1OR <- lm(W_O_moves~B_R_moves,data)
revfit2OR <- lm(W_O_moves~B_R_moves,winData)
revfit3OR <- lm(W_O_moves~B_R_moves,losData)
revfit4OR <- lm(W_O_moves~B_R_moves,drawData)

revfit1QB <- lm(W_Q_moves~B_B_moves,data)
revfit2QB <- lm(W_Q_moves~B_B_moves,winData)
revfit3QB <- lm(W_Q_moves~B_B_moves,losData)
revfit4QB <- lm(W_Q_moves~B_B_moves,drawData)
revfit1QK <- lm(W_Q_moves~B_K_moves,data)
revfit2QK <- lm(W_Q_moves~B_K_moves,winData)
revfit3QK <- lm(W_Q_moves~B_K_moves,losData)
revfit4QK <- lm(W_Q_moves~B_K_moves,drawData)
revfit1QN <- lm(W_Q_moves~B_N_moves,data)
revfit2QN <- lm(W_Q_moves~B_N_moves,winData)
revfit3QN <- lm(W_Q_moves~B_N_moves,losData)
revfit4QN <- lm(W_Q_moves~B_N_moves,drawData)
revfit1QO <- lm(W_Q_moves~B_O_moves,data)
revfit2QO <- lm(W_Q_moves~B_O_moves,winData)
revfit3QO <- lm(W_Q_moves~B_O_moves,losData)
revfit4QO <- lm(W_Q_moves~B_O_moves,drawData)
revfit1QQ <- lm(W_Q_moves~B_Q_moves,data)
revfit2QQ <- lm(W_Q_moves~B_Q_moves,winData)
revfit3QQ <- lm(W_Q_moves~B_Q_moves,losData)
revfit4QQ <- lm(W_Q_moves~B_Q_moves,drawData)
revfit1QR <- lm(W_Q_moves~B_R_moves,data)
revfit2QR <- lm(W_Q_moves~B_R_moves,winData)
revfit3QR <- lm(W_Q_moves~B_R_moves,losData)
revfit4QR <- lm(W_Q_moves~B_R_moves,drawData)

revfit1RB <- lm(W_R_moves~B_B_moves,data)
revfit2RB <- lm(W_R_moves~B_B_moves,winData)
revfit3RB <- lm(W_R_moves~B_B_moves,losData)
revfit4RB <- lm(W_R_moves~B_B_moves,drawData)
revfit1RK <- lm(W_R_moves~B_K_moves,data)
revfit2RK <- lm(W_R_moves~B_K_moves,winData)
revfit3RK <- lm(W_R_moves~B_K_moves,losData)
revfit4RK <- lm(W_R_moves~B_K_moves,drawData)
revfit1RN <- lm(W_R_moves~B_N_moves,data)
revfit2RN <- lm(W_R_moves~B_N_moves,winData)
revfit3RN <- lm(W_R_moves~B_N_moves,losData)
revfit4RN <- lm(W_R_moves~B_N_moves,drawData)
revfit1RO <- lm(W_R_moves~B_O_moves,data)
revfit2RO <- lm(W_R_moves~B_O_moves,winData)
revfit3RO <- lm(W_R_moves~B_O_moves,losData)
revfit4RO <- lm(W_R_moves~B_O_moves,drawData)
revfit1RQ <- lm(W_R_moves~B_Q_moves,data)
revfit2RQ <- lm(W_R_moves~B_Q_moves,winData)
revfit3RQ <- lm(W_R_moves~B_Q_moves,losData)
revfit4RQ <- lm(W_R_moves~B_Q_moves,drawData)
revfit1RR <- lm(W_R_moves~B_R_moves,data)
revfit2RR <- lm(W_R_moves~B_R_moves,winData)
revfit3RR <- lm(W_R_moves~B_R_moves,losData)
revfit4RR <- lm(W_R_moves~B_R_moves,drawData)

